### ISSUE TITLE
Introduction to machine learning

### ISSUE THREAD

**Issue by thomthom** [trondheim-machine-learning-meetup/meetups#18]
Hadde en liten samtale med folk fra Hackheim om maskinlæring. Flere som var interessert og nysgjerrig i tema - men skulle gjerne hatt mer info.

Tema ble tatt opp på Work-Work og Digs, også der var det interesse.

Det som flere var interessert i var noe ala "maskinlæring for dummies". Lavterskel introduksjon til hva man kan gjøre med teknologies ang hvordan man kommer i gang. Gjerne noe praktisk der man ikke nødvendigvis trenger å forstå all matematikken, men heller hvordan man bruker de verktøy om er der ute.

Så at det mulig har vært en slik type meetup allerede?
https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/238379730/

Til referanse, en trå i Hackheim's FB gruppe: [Hackheim](https://www.facebook.com/groups/hackheim/permalink/1670516073020814/?comment_id=1671606709578417&reply_comment_id=1672361729502915&ref=notif&notif_t=group_comment&notif_id=1505853357491633)

Fikk høre om denne meetuppen i forbindelse med dette. Hva tenker dere om dette?

**Comment by iver56** [comment]
Tenker at det høres ut som en god idé 👍 Jeg har kjørt noen hands-on workshops før, blant annet den du nevner. Det som er lurt i en workshop er at man har en konkret oppgave man prøver seg på. I en slik workshop, hvor deltakere prøver seg på hands-on maskinlæring, ser jeg på det som et minstekrav at de har vært borti programmering før. Hvis deltakerne er folk som ikke har vært borti programmering, er det bedre med en lett forståelig presentasjon med eksempler, og ingen programmering. Eksempler på slike presentasjoner:
* https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/238390273/ (Lars Eidnes)
* https://www.facebook.com/events/259976261184408/ (Sigurd Stendal og Odd Jostein Svendsli)

**Comment by thomthom** [comment]
Tror nok det er interesse for begge deler. Personlig foretrekker jeg den som inkluiderer programmering. :)
Er dette noe hvor vi også kan kombinere noe fysisk? Mekke sammen noe på Hackheim's verksted som kan driftes av maskinlæring?

**Comment by iver56** [comment]
Ja, det høres ut som en god idé. Kanskje vi kan møtes på Work-Work og brainstorme oss fram til noe?

**Comment by thomthom** [comment]
Ja, jeg sitter på Work-Work til daglig - så det passer bra. :)
Men jeg har som regel møter mellom 17-18.

**Comment by iver56** [comment]
Jeg stikker gjerne innom i dag. Har en idé

**Comment by thomthom** [comment]
Har litt knapt med tid i dag. Hva med i morgen?

**Comment by iver56** [comment]
Ja, det funker

**Comment by iver56** [comment]
Satser på å dukke opp en gang mellom kl. 15:20 og kl. 16. Passer det?

**Comment by thomthom** [comment]
Yup!

**Comment by iver56** [comment]
Henger i baren nå

**Comment by thomthom** [comment]
Kommer ned straks.

**Comment by iver56** [comment]
Vi i AIA Science kan kjøre en "machine learning basics" workshop i september eller oktober, etter at vi har flyttet til Piren.

Nøkkelord:
* Tekstklassifisering (bag of words)
* Neural network, backpropagation (keras)
* Random forest (scikit-learn)

@askskro

**Comment by thomthom** [comment]
Intresant. For meg passer det bedre etter første uke i Oktober. I slutten av September er jeg ikke på kontinentet.

**Comment by askskro** [comment]
Inspirert av hvor mange som ikke rakk opp hånden under et par av spørsmålene til publikum på forrige meet up. 
Ser også gjerne at det blir i oktober. 
Jeg kan skrive et forslag til tema og plan i.l.a. første uke av september.

**Comment by iver56** [comment]
24. oktober eller 25. oktober?

**Comment by askskro** [comment]
25. oktober kanskje?

Uansett det jeg tenkte var at på forrige meetup (TCN) var det såpass mange som ikke rakk hånden i været da det ble spurt om kjennskap til maskinlæring både i teori og praksis at det kunne vært kjekt med en intro. 

I det hele tatt vil formålet være og utvide kretsen rundt maskinlæring i Trondheim. Ganske likt "Workshop: Kom i gang med deep learning" som ble holdt i fjor med andre ord. Men en workshop med dette temaet kunne kanskje med fordel bli en årlig greie?

Så det jeg tenkte rent praktisk var en todelt meetup hvor del en blir en liten teoretisk innføring og del to blir litt praktisk. P.g.a. begrenset tid tipper jeg vi holder oss til deep learning, (kanskje vi burde bytte tittel?).
Teoretisk del: slides med historie/inspirasjon(?), bruksområder, litt teoretisk  gjennomgang av et standard feed forward network, veldig kort om andre modeller RNN/CNN.
Praktisk del, kan gjøres litt likt Iver sin RNN meetup med oppgaver og hjelp. I så fall hadde det vært kjekt å ha flere til å gå rundt på gulvet. Ting som burde dekkes kan være sklearn og Keras. 

Forslag til intro tekst:

>- Are you curious about machine learning?
>- Have you been meaning to start out with machine learning but not found the time?
>- Have you had that Andrew Ng coursera course on your to do list for more than a year?
>- Are you familiar with the topic and eager to try out something but don't know where to start?
>- Do you just want to put deep learning expert on your CV like all the cool kids?
>- Do you just enjoy free food?
>
>Do you perhaps need just a little push?
>
>If this is you or perhaps a friend or colleague, you're all welcome to a session where we explore the topic of machine learning and gets some hands on experience. There will be a talk introducing the topic and and going into some details (softly). There will also be a practical part where you can try out some problems of various difficulty and get some assistance, we will use scikit-learn and Keras. 
>
>There will be free food(?). 
>
>More info coming.


Er veldig åpen for feedback både på plan for gjennomføring. Og også forsåvidt på om dette temaet i det hele tatt trengs. Jeg foreslår Iver at vi venter litt på feedback før du lager event.

**Comment by thomthom** [comment]
24 passer bedre for min del.

**Comment by iver56** [comment]
@askskro Du snakket om å flytte meetupen til starten av November, på grunn av Trondheim Developer Conference, ikke sant? Hvilken dato ser du for deg?

**Comment by iver56** [comment]
Aktuell dato: Torsdag 15. november

**Comment by iver56** [comment]
Annonsert: https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/255551218/

Nå er det bare å invitere folk, @thomthom :)
