### ISSUE TITLE
Image style transfer and other creative AI techniques

### ISSUE THREAD

**Issue by MariaSaether** [trondheim-machine-learning-meetup/meetups#22]
The presentation will explain how and why the algorithm for neural style works. It will also cover the development of style transfer showing off some of the cool result achieved.

**Comment by MariaSaether** [comment]
Vi i Inmeta kjører dette som tema for meetup i Oslo i november og kan kjøre tilsvarende i Trondheim før jul evt.

**Comment by iver56** [comment]
God idé! Hvis du vil, kan jeg også presentere noe relatert til style transfer på samme meetup. Har du tanker om dato?

**Comment by MariaSaether** [comment]
Supert.
Ang. dato så er vi relativt åpne. Det så ut som om det var noe på gang hos Fundator nå i november, men hvis det ikke blir noe av så kan vi godt forøke å få det til i slutten av mnd. evt. 1.uke i desember. Vi bør vel legge inn minst et par ukers varsel i forkant av meetupen.

Vennlig hilsen Maria

**Comment by iver56** [comment]
Det blir meetup hos Fundator 23. november. Kanskje det passer bra med en meetup om Style Transfer en gang mellom 7. desember og 15. desember?

**Comment by MariaSaether** [comment]
OK, sjekker om Solveig har anledning den uka.
Når det gjelder neste meetup 23.nov. så burde vel den annonseres så snart som mulig, slik at folk får tid til å sette av datoen?

Vennlig hilsen Maria

**Comment by iver56** [comment]
Flott! Ja, meetupen 23. November ble nylig annonsert: https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/243950552/

Du må gjerne invitere Inmeta-folket

**Comment by iver56** [comment]
@MariaSaether Har du fått respons fra Solveig? Eventuelt kan vi flytte det til første halvdel av januar, for å få med flere deltakere. Førjulstida er travel for mange (f.eks. eksamensperiode).

**Comment by MariaSaether** [comment]
Hei,
Ja, jeg tenker det samme. Solveig holdt denne sesjonen på ml-meetup i Oslo i uka her med bra respons. Vi satser på 1.halvdel av januar, så blir den ikke så tett på gårsdagens og juleferien.

Hvordan var det i går?

Mvh Maria
________________________________

**Comment by iver56** [comment]
Greit da sier vi det, og så spikrer vi dato litt senere.

Meetupen i går ble en suksess 👍 Jeg fikk inntrykk av at folk likte presentasjonen, og at det ble god stemning med snacks og greier etterpå.

**Comment by iver56** [comment]
@MariaSaether Hva tenker du om dato? Jeg tenker siste halvdel av januar, for å gi folk tid til å sette av datoen. Hva med torsdag 25. januar? Big Data-meetupen har forresten tentativt satt opp meetup 17. januar.

**Comment by iver56** [comment]
@MariaSaether Er det fortsatt aktuelt å avholde denne meetupen? Hvis ja, la oss finne en dato som passer :) Forslag?

**Comment by MariaSaether** [comment]
Hei ! Foreslår å kjøre Style-transfer meetup mandag 26.februar på Work-Work. Passer datoen for din del? 
Inmeta kan sponse pizza/brus som vanlig. Skal du el. jeg koordinere med work-work? (...evt. sjekke at datoen er ledig der)

**Comment by iver56** [comment]
Jeg kan ordne med booking av møterom.

Mandag 26. februar er møterommet opptatt fra ca kl. 19. Er det du eller @WillRNaylor som allerede har booket møterommet på det tidspunktet? Hvis det er noen andre enn oss som har booket møterommet da, er det sikkert best å velge en annen dato eller et annet sted

**Comment by MariaSaether** [comment]
Tviler på at William har booket det. Sjekker med han. Ang. alt. dato så må jeg da avklare med Solveig om hvorvidt hun har anledning en av de andre dagene den uka.
Hva med å kjøre meetup mand. 26. kl. 16:30-19? Selve meetup'en tar ca. 1 time + evt. diskusjoner.

**Comment by iver56** [comment]
26. februar funker for meg, men jeg synes at kl. 16:30 er for tidlig. Mange er vanligvis ikke ferdig på jobb før kl. 17. Fikk også tilbakemelding om at kl. 17:00 var litt tidlig da Fundator valgte det tidspunktet på [Machine learning Anomaly Detection with AIS in Real Time](https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/243950552/) i fjor høst.

**Comment by WillRNaylor** [comment]
Bare for å bekrefte at det ikke var meg som booket Work Wok.

**Comment by MariaSaether** [comment]
OK. Da har vi 2 muligheter: 
Mandag kl. 17:30-18:30 + evt. sp.m. (evt. starte kl. 17)
Tirsdag 27.02, f.eks. fra kl. 18:00
@iver56 kan du sjekke om lokalet er ledig på tirsdag?

**Comment by iver56** [comment]
Ja, møterommet på Work-Work er ledig på tirsdag 27. feb

**Comment by MariaSaether** [comment]
OK, book møterommet for tirsdag kl. 18-19:30, så kjører vi meetup da. Solveig har bekreftet at hun har anledning.
Kanskje vi allerede nå skal beg. å tenke på dato for påfølgende meetup med Lime som tema? F.eks. uke 12, som er uka før påske.

**Comment by WillRNaylor** [comment]
Jeg er fri hvilket som helst tid og dag i uke 12, og denne høres bra til meg.

**Comment by iver56** [comment]
Jeg har booket møterommet på Work-Work tirsdag 27. februar 18:00-20:00

Vi trenger en liten beskrivelse av meetupen. Jeg kan også skrive 1-2 setninger om noen av mine egne eksperimenter som jeg kan vise fram under meetupen.

Re LIME uke 12: Ja, greit for meg

**Comment by MariaSaether** [comment]
[Style transfer meetup.pptx](https://github.com/trondheim-machine-learning-meetup/meetups/files/1703326/Style.transfer.meetup.pptx)

@iver56 Se vedlegg for forslag til tekst/bilder for Style transfer-meetup. Jeg kan lage invitasjon, evt. kan du legge til noen ord om det du vil snakke om og lage invitasjonen.

**Comment by iver56** [comment]
Ser bra ut! Jeg kan opprette en draft av meetupen. Jeg legger til Maria som co-organizer. Jeg tok meg den frihet å legge til en liten beskrivelse av det jeg tenkte å vise fram.

Hvis det er ønske om endringer, er det bare å gi beskjed før jeg annonserer meetupen i morgen.

```
This meetup features two presentations:

1) Since the algorithm for Style Transfer was published by Gatys et al. we’ve seen a wide range of artistic photos achieved by combining style and content from different images.

The algorithm went viral, with apps like Prisma, Facebook and Instagram lavished with Van Gogh, Munch, Monet etc. styled images.

The presentation will explain how and why the algorithm for neural style works. It will also cover the development of style transfer showing off some of the cool results achieved.

Presenter: Solveig Masvie from Inmeta

2) In the second presentation, Iver Jordal from AIA Science will show some examples where he

* taught a feedforward neural network to output logos and morph between them
* used HyperGAN to train a model that generated images in his favorite art style
* used a Travelling Salesman Problem solver to create smooth transitions between images generated by HyperGAN
* used the "deep dream" technique to amplify anything that looked like the number 7
* used style transfer in a digital art competition, and nobody seemed to notice that AI was involved

Inmeta will provide pizza and soft drinks. Well met!

PS: In the featured photo, the beer has been style transferred to match Mona Lisa, and then integrated in her lap. Because we can.
```

https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/247584393/

**Comment by iver56** [comment]
Meetupen er nå publisert og annonsert

**Comment by MariaSaether** [comment]
Supert ??
________________________________

**Comment by MariaSaether** [comment]
Hei Iver! Har ikke sjekket om området nede v/baren er ledig, men ser at det nå nærmer seg 40 påmeldte til meetup. Av erfaring er det alltid en del som ikke møter, men rommet oppe er vel beregnet til ca. 30 er det ikke? Skal vi sette stop for påmelding og heller åpne for venteliste?

Vennlig hilsen Maria

**Comment by iver56** [comment]
Det er lagt inn en begrensning på 42 deltakere. Hvis flere enn det prøver å melde seg på, blir det venteliste. I fjor høst hadde vi en meetup med begrensning på 45 deltakere, og det gikk bra. Det er plass til ca 36 personer.
________________________________

**Comment by MariaSaether** [comment]
Den er god!

Vennlig hilsen Maria

**Comment by iver56** [comment]
@MariaSaether Er pizzaen bestilt? Jeg kommer tidlig, ca. kl. 1730, for å hjelpe til med å møblere møterommet på Work-Work.

**Comment by MariaSaether** [comment]
Hei Iver!
Ja, har bestilt pizza til 17:45 og kommer også opp ca. 17:30 med drikke etc. så da sees vi der 😊

Vennlig hilsen Maria
