### ISSUE TITLE
An Empirical Evaluation of Generic Convolutional and Recurrent Networks for Sequence Modeling

### ISSUE THREAD

**Issue by iver56** [trondheim-machine-learning-meetup/meetups#24]
TL;DR: It turns out that CNN is actually better than LSTM/GRU in nine out of eleven cases of sequence modelling. It's worth a meetup.

https://arxiv.org/abs/1803.01271

https://github.com/locuslab/TCN

**Comment by iver56** [comment]
> Et annet tema som er veldig interessant, som jeg har jobbet litt med i det
> siste, er Temporal Convolutional Networks.
> 
> https://arxiv.org/abs/1803.01271
> 
> Disse holdte presentasjon på ICLR i mai, og har lagt ut koden tilhørende
> paper'et, så det er lett å reprodusere.
> 
> Flere antyder at det kan være ting som tyder på at dette bør være den nye
> "standarden" for sekvensmodellering.
> 
> https://towardsdatascience.com/the-fall-of-rnn-lstm-2d1594c74ce0
> 
> 
> Jeg har brukt ulike versjoner av TCN på egne datasett med gode resultater,
> særlig på type høydimensjonale tidsserier fra sensordata.
> 
> Hva tror du om en todelt med tittelen "Mutlivariate time series forecasting
> with Temporal Convolutional Networks", der del 1 er teoretisk rettet, og
> del 2 er praktisk (walkthrough av en notebook)?
> 
> Mvh
> Thomas

@thomasht86 Todelt meetup høres bra ut! Hva tenker du om lokale?

**Comment by iver56** [comment]
Her er noen alternativer:
* NTNU Accel, Kongens Gate 30
* Norconsult sine lokaler
* NTNU Gløshaugen
* DIGS (da må vi spørre om de har mulighet til å sette opp nok bord og strømpadder)
* Work-Work (men da blir det bare plass til ca. 20 personer, siden de har bygd om)

@thomasht86 Hva foretrekker du?

**Comment by thomasht86** [comment]
Vi kan gjerne ha det hos oss ja. Fikk akkurat bekrefta at Norconsult
sponser pizza og øl også. :)
16. August passer veldig bra ser jeg i kalenderen her. Funker det?

Den man. 16. jul. 2018, 09:47 skrev Iver Jordal <notifications@github.com>:

**Comment by iver56** [comment]
Perfekt! Ja, det funker.

Hvis du sender meg tittel, beskrivelse, adresse og kanskje et bilde, så kan jeg legge inn eventen på meetup.com, og legge inn deg som co-organizer, slik at du kan oppdatere eventen ved behov

**Comment by thomasht86** [comment]
Temporal Convolutional Networks - Dethroning RNN's for time series and
sequence modelling

In this meetup we will be exploring Temporal Convolutional Networks(TCN), a
general architecture for modelling (multidimensional) time series data,
which recently has achieved state-of-the-art results on a number of
challenging sequence modelling benchmarks. (https://arxiv.org/abs/1803.01271
)

The meetup will have a theoretical part, where will look at the components
of the architecture, and compare it to other methods for modelling time
series. In the second part we will demonstrate an application of a TCN to
classify sensor data in real-time.

Basic knowledge about neural networks is an advantage.

Location:
Norconsult Informasjonssystemer,
Klæbuveien 127B, 6.etg. (Inngang fra side mot RBK's treningsfelt)

Den man. 16. jul. 2018, 11:19 skrev Iver Jordal <notifications@github.com>:

**Comment by iver56** [comment]
Flott! Jeg legger inn en draft av arrangementet nå.

Meetup.com mente at tittelen var 9 tegn for lang. Jeg korter ned til "Temporal Convolutional Networks - Dethroning RNNs for sequence modelling". Dette kan du endre på meetup.com hvis du vil.

Jeg legger gjerne inn et illustrasjonsbilde. Hvis du har noe som passer bedre, er det bare å endre/fjerne det.

![bilde](https://user-images.githubusercontent.com/1470603/43022777-ac0c3e8e-8c68-11e8-8951-ca36fbc982d1.png)

Kanskje legge til en liten setning om at Norconsult sponser mat/drikke?

Hva tenker du om tidspunkt? Hva med kl. 18?

Jeg setter foreløpig en maksgrense på 60 deltakere. Denne kan endres ved behov.

Greit å annonsere meetupen i morgen?

**Comment by thomasht86** [comment]
Veldig bra.

Ja. Norconsult stiller med mat/drikke. Kult bilde. :)
Tenkte å ta det rett etter jobb, så 1700 hadde passet enda bedre. Da får
folk pizza i middagstid også. Er ikke det greit? :)

Fint å annonsere i morgen ja!


Den fre. 20. jul. 2018, 22:10 skrev Iver Jordal <notifications@github.com>:

**Comment by iver56** [comment]
Ja, det er greit. Jeg oppdaterte tidspunktet til 17.00 og annonserte meetupen 👍

**Comment by iver56** [comment]
@thomasht86 Vi nærmer oss maksgrensen på 60 deltakere. Er det aktuelt å øke grensen?

**Comment by thomasht86** [comment]
Hei!
Så gøy! :)
Vi sjekker opp litt nærmere ang. plass i lokaler.
Kommer tilbake til deg!

Den ons. 8. aug. 2018, 15:52 skrev Iver Jordal <notifications@github.com>:

**Comment by thomasht86** [comment]
Hei!
Da har vi sjekket opp litt og vi kan utvide til 70 stk. :)

Den tor. 9. aug. 2018, 09:26 skrev Thomas Thoresen <
thomas.h.thoresen@gmail.com>:

**Comment by iver56** [comment]
Flott! Jeg har økt grensen til 70 nå :)
Husk at ikke alle som er påmeldt møter opp. Gang med noe sånt som 0.8 for å få et mer realistisk estimat på antall deltakere.

**Comment by iver56** [comment]
Takk for et bra arrangement! Flott at du delte slides også
