### ISSUE TITLE
Machine learning algorithms for churn- and time to event prediction

### ISSUE THREAD

**Issue by iver56** [trondheim-machine-learning-meetup/meetups#26]
https://github.com/ragulpr/wtte-rnn

@askskro

**Comment by iver56** [comment]
@askskro Tentativ dato: 24. mai

**Comment by askskro** [comment]
Tror vi kan sette den datoen som sikker for min del nå.

**Comment by iver56** [comment]
Jeg jobber med å finne lokale. Har tatt kontakt med DIGS.

I mellomtida hadde det vært fint å få på plass en beskrivelse og kanskje et bilde til arrangementet :)

@askskro Vil du skrive?

**Comment by askskro** [comment]
Nice.
Skal prøve å få skrevet noe i løpet av dagen.

**Comment by iver56** [comment]
https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/250298421/

**Comment by iver56** [comment]
@askskro Legg gjerne inn presentasjonen og link i README.md 👍
