### ISSUE TITLE
InMeta, spring 2019?

### ISSUE THREAD

**Issue by iver56** [trondheim-machine-learning-meetup/meetups#28]
@WillRNaylor Would you be interested in hosting a meetup about a machine learning-related topic of choice this autumn? Or maybe any of your colleagues?

**Comment by WillRNaylor** [comment]
I'll get back to you in a bit, as I have asked other in inmeta. For me, it's more likely that something will suit at the start of next year.

**Comment by iver56** [comment]
Thanks! I look forward to hearing from you soon 👍

**Comment by WillRNaylor** [comment]
I haven't gotten any positive answers from anyone here, so the answer from Inmeta this autumn will be we won't give a presentation. How are you going for presentations? It seems there are a couple of workshops coming up maybe? And then I guess you'd like one more presentation to round out the year?

**Comment by iver56** [comment]
Thanks for the response!

Yes, the next two events will probably be hands-on, as in participants will need to bring their own laptop. I do not have anything lined up for November and December yet, but it would indeed be nice to have a meetup in each of those months as well. Both workshops and presentations are appreciated.

**Comment by WillRNaylor** [comment]
Hey, I just added a new issue for medical imaging, as I initially didn't see/remember this one.
