### ISSUE TITLE
Klassifisering av tekst

### ISSUE THREAD

**Issue by iver56** [trondheim-machine-learning-meetup/meetups#3]

**Comment by iver56** [comment]
Mai

**Comment by erlendvollset** [comment]
Torsdag 25. Mai Kl. 1800

**Comment by iver56** [comment]
Har booka møterommet på Work-Work fra 17:45 til 20:00

**Comment by iver56** [comment]
@erlendvollset Hei :) Jeg tenker at vi burde annonsere denne workshopen på meetup.com snart. Det vi trenger nå er en kort beskrivelse av arrangementet og grønt lys fra deg. Detaljer kan eventuelt spikres senere.

**Comment by iver56** [comment]
Utsatt

**Comment by iver56** [comment]
https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/246929884/
