### ISSUE TITLE
Kaggle

### ISSUE THREAD

**Issue by askskro** [trondheim-machine-learning-meetup/meetups#32]
Suggestions for things to cover.
* Intro to kaggle
* How to get started with competitions?
* Lessons from previous competitions?
* Finding team members in Trondheim?

Anyone that has a lot of experience here?

**Comment by iver56** [comment]
Good idea! Perhaps @top-quarks or @thomasht86 want to share some Kaggle-related tips and tricks?

**Comment by thomasht86** [comment]
Yes! 
Have thought about this for some time. Definitely would be awesome to get some more kagglers from Trondheim. I am sure Norconsult can host a meetup for this in January?
I don't know @top-quarks, but we could probably share the meetup if you would like? 

Let me know if you want us to host it, and I'll get an approval and schedule a date asap. =)

**Comment by iver56** [comment]
Yes, you are welcome to host it in January 👍 That would be nice

top-quarks is also known as icecuber on Kaggle

**Comment by bjornamr** [comment]
Awesome, @thomasht86. More kaggling in Trondheim would be fun. I will defiently come!

**Comment by thomasht86** [comment]
Cool!

What do you think about Wednesday Jan 16th?
@top-quarks, do you want to present something? Maybe a walkthrough of a
competition? =)




Den tor. 15. nov. 2018 kl. 23:05 skrev Bjørnar Moe Remmen <
notifications@github.com>:

**Comment by iver56** [comment]
Yeah, Jan 16th works

**Comment by iver56** [comment]
@thomasht86 Skal vi begynne å tenke på å annonsere arrangementet? Sikkert lurt å gjøre det før juleferien. Vi trenger en beskrivelse og et klokkeslett

**Comment by thomasht86** [comment]
Getting started with Kaggle

Beskrivelse:
Kaggle is the worlds largest platform for competitive machine learning. The
results from Kaggle competitions have pushed the state-of-the-art in many
domains, and the level of competion is fierce.
In this workshop Thomas Thoresen will give an introduction to the platform,
share some tips&tricks, and experiences from previous competitions, with
focus on Zillow's home valuation prediction competition (
https://www.kaggle.com/c/zillow-prize-1)

Tidspunkt kl. 18

Ok?

Thomas

Den man. 10. des. 2018 kl. 14:29 skrev Iver Jordal <notifications@github.com

**Comment by iver56** [comment]
Ja, det ser bra ut!

Her er to spørsmål som vi kanskje bør besvare i beskrivelsen:

* Trenger folk å ta med laptopen sin?
* Blir det noe å bite i under workshopen?

**Comment by thomasht86** [comment]
Ja, (ingen installasjoner trengs, vi bruker Kaggle kernels)
og JA, selvfølgelig. Norconsult stiller med mat og drikke! =)

Den man. 10. des. 2018 kl. 19:23 skrev Iver Jordal <notifications@github.com

**Comment by iver56** [comment]
Flott! Ser det greit ut?

https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/257108167/

Jeg kan annonsere meetupen når du gir grønt lys

**Comment by thomasht86** [comment]
Jepp!

Den man. 10. des. 2018, 19:42 skrev Iver Jordal <notifications@github.com:

**Comment by iver56** [comment]
Nå har jeg annonsert meetupen 👍

**Comment by iver56** [comment]
@thomasht86 Begynner du å bli klar for arrangementet i morgen? Bare si fra hvis du trenger hjelp med noe

**Comment by thomasht86** [comment]
Jada, begynner å bli klar!

Takk for det.

Sier fra dersom vi trenger noe =)

Den tir. 15. jan. 2019 kl. 09:47 skrev Iver Jordal <notifications@github.com

**Comment by thomasht86** [comment]
Hei!
Har jobbet en del med MlFlow (mlflow.org) i det siste. Synes det er veldog
nyttig, og kan gjerne kjøre en meetup med litt intro og "getting started"
med det. Tror du det kunne vært interessant? :)

Thomas

tor. 17. jan. 2019, 11:08 skrev Iver Jordal <notifications@github.com>:

**Comment by iver56** [comment]
Ja, det er et fint tema for en meetup :) Kjør på! Jeg lager et nytt issue:
https://github.com/trondheim-machine-learning-meetup/meetups/issues/35
