### ISSUE TITLE
Medical image classification and segmentation

### ISSUE THREAD

**Issue by WillRNaylor** [trondheim-machine-learning-meetup/meetups#33]
I, William, could hold a presentation on our work on classification of polyps from within medical imaging. We could also provide some code, maybe though notebooks.azure.com, as we are mostly working with public datasets, and some models can be trained relatively quickly, but most models need GPU support for training in normal times so probably don't work easily.

Could be done any time in 2019, after January.

**Comment by WillRNaylor** [comment]
A slight idea is also to spend 5 mins introducing notebooks (in the case that we share code).

**Comment by iver56** [comment]
Great! February would be perfect

**Comment by iver56** [comment]
@WillRNaylor which date do you prefer?

And what venue should we use?

1) Pirsenteret, meeting rooms Munken & Holmen (1600 NOK)
2) DIGS event room (~2200 NOK)
3) The bar at Work-Work (unknown price)
4) Inmeta?
5) ...

**Comment by WillRNaylor** [comment]
Hey Ivar, does the 26th of Feb work? The other person working on the Project (Huamin) will be away the first half of Feb, so it'd be great to do it when she's back.

As for the room, it makes sense to have it in Pirsenteret. Maria has sent an email about the room to pirsenter, so I'll get back to you as to what they suggest.

**Comment by iver56** [comment]
Sounds good!

**Comment by iver56** [comment]
I was in a meeting with Maria and ECDE earlier today. ECDE said that they will cover the meeting room costs for this meetup group. We can use either Munken & Holmen (~35 seats) or auditorium A150 (more than 100 seats). Pirkanten Spiseri can provide food for the event (the plan is 50 NOK per person), and I'll ask if Den Norske Dataforening can cover that cost. Maria suggested that we choose auditorium A150.

You and I will both get access with our Pirsenteret access card, so we won't have to borrow an access card.

What we need now is an event description. @WillRNaylor can you please write one? Thanks!

**Comment by WillRNaylor** [comment]
The above sounds great, although I might not get the description to you before say Saturday.

**Comment by WillRNaylor** [comment]
Summary:

Work and code will be presented from a project looking into automatic detection of polyps - growths within the intestines that can cause cancer. Polyps are detected based on normal RGB images taken during colonoscopies. We will look at image segmentation and classification algorithms. Expect many disgusting medical images!

**Comment by WillRNaylor** [comment]
I wasn't sure how to send a picture over this, but maybe if you add me as an admit of the Meetup page I'll be able to add an image of a polyp with some detection in there somewhere.

**Comment by iver56** [comment]
Thanks! I updated the event description and set your member role to Assistant Organizer. You should be able to edit the draft and upload your photo here:
https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/258320641/

**Comment by iver56** [comment]
I've sent an email to DND about the food

**Comment by iver56** [comment]
They approved the request. I will now add info on food to the meetup and then announce it.

**Comment by iver56** [comment]
Announced

**Comment by WillRNaylor** [comment]
Hey, er vi klar for i morgen i forhold til mat og rom? Jeg ser på meetup nettsiden at det er i A150, så antar at alt er klar, men bedre å sjekk.

Jeg har slides og en notebook klar, og trenger ikke noe spesiell. Ses i morgen.

**Comment by iver56** [comment]
Ja, alt er klart. Hvis du vil, kan du sjekke at du har tilgang til rommet og at utstyret (projektor og mikrofon) fungerer.

Vi sees i morgen 👍
