### ISSUE TITLE
MLflow

### ISSUE THREAD

**Issue by iver56** [trondheim-machine-learning-meetup/meetups#35]

**Comment by iver56** [comment]
@thomasht86 Har du forslag til dato?

**Comment by thomasht86** [comment]
Onsdag 29 mai kanskje? Dagen før Kristi himmelfartsdag...

ons. 10. apr. 2019 kl. 09:55 skrev Iver Jordal <notifications@github.com>:

**Comment by iver56** [comment]
Ja, det høres bra ut. Kjøre arrangementet hos dere i Norconsult da, på samme måte som før?

**Comment by thomasht86** [comment]
Jepp!

Da sier vi det. Skal få laget en beskrivelse snart. =)

tor. 11. apr. 2019 kl. 09:27 skrev Iver Jordal <notifications@github.com>:

**Comment by iver56** [comment]
Hei :) Det begynner å bli på tide å annonsere meetupen. Hvordan går det med beskrivelsen av arrangementet?

**Comment by thomasht86** [comment]
Det gjør det!

Trodde jeg hadde sendt det jeg. :)
Beklager.

Hva med noe sånt?

MLFlow is an open source platform to manage the ML lifecycle.
It facilitates tracking of experiments, reproducibility and deployment of
ML models through a simple Python API.
It is also integrated as a part of Databricks, but can be run both on a
local machine and/or a cluster.

In this meetup we will go through a "end-to-end" ML-project with focus on
how MLFlow is useful in each part of the workflow.

Pizza and drinks will be provided by Norconsult Informasjonssystemer.

-Thomas

man. 6. mai 2019 kl. 14:35 skrev Iver Jordal <notifications@github.com>:

**Comment by iver56** [comment]
Perfekt! Skal jeg prøve å finne et passende bilde? Starte kl. 18:00, slik som forrige gang?

**Comment by thomasht86** [comment]
Ja, og ja! :)

man. 6. mai 2019 kl. 14:52 skrev Iver Jordal <notifications@github.com>:

**Comment by iver56** [comment]
https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/260536769/

Ser det greit ut? Hvis du gir grønt lys, så skal jeg annonsere arrangementet :)

**Comment by thomasht86** [comment]
Ser bra ut! Kjør på :)

man. 6. mai 2019 kl. 14:58 skrev Iver Jordal <notifications@github.com>:

**Comment by thomasht86** [comment]
Hei!
Er det en enkel måte å sende e-post til meetup-attendees?
Eller får de varsling om jeg poster en message under eventen?

Har litt forberedelser de som skal følge meetup'en på egen PC trenger å
gjøre. =)

-Thomas

man. 6. mai 2019 kl. 15:05 skrev Thomas Thoresen <
thomas.h.thoresen@gmail.com>:

**Comment by iver56** [comment]
Morn :) Du er lagt til som event-host. Har du tilgang til denne knappen?

![bilde](https://user-images.githubusercontent.com/1470603/58396076-66604b00-804b-11e9-9bd2-e29d137f5d72.png)

Hvis ikke, så kan det være fordi at jeg har lagt til feil konto som event-host. Det ser ut som du har to forskjellige kontoer som ligner

![bilde](https://user-images.githubusercontent.com/1470603/58396140-ae7f6d80-804b-11e9-99b3-361a9d487dc7.png)

Skal jeg prøve å legge til den andre kontoen din som event-host?

**Comment by thomasht86** [comment]
Logget inn med facebook nå og da fikk jeg tilgang til den. Takk! =)


man. 27. mai 2019 kl. 06:51 skrev Iver Jordal <notifications@github.com>:

**Comment by iver56** [comment]
Takk for arrangementet! :)
