### ISSUE TITLE
Operationalizing Machine Learning model with SQL 2016 R Services : field report

### ISSUE THREAD

**Issue by iver56** [trondheim-machine-learning-meetup/meetups#6]
> In this presentation we will give a retrospective on implementing a production ready Machine Learning service at the Norwegian Labor Inspection Authority (Arbeidstilsynet). 
> 
> We will use the project as an example case for using Microsoft SQL Server 2016 R Services as a production environment for a Machine Learning service.
> 
> Presenter: Anton Eskov, Inmeta
> 
> Pizza and softdrinks will be provided :)

**Comment by iver56** [comment]
Når/hvor?

**Comment by MariaSaether** [comment]
Hei! OK om Anton kjører denne 10.mai? (onsdag) evt. en av de andre dagene den uka?

**Comment by MariaSaether** [comment]
Vi har også andre presentasjoner vi kan kjøre som har slått godt an i Oslo på tilsvarende Meetups

**Comment by iver56** [comment]
Ja, det høres bra ut 👍 Kl. 18 @ Work-Work? Eller foretrekker du å bruke egne lokaler?

**Comment by MariaSaether** [comment]
Sjekker med work-work ang. servering og kommer tilbake til deg med litt mer detaljer om sted/servering.

**Comment by iver56** [comment]
@MariaSaether Har du funnet ut noe mer om sted/servering? Jeg tenker at det er lurt å annonsere meetupen ganske snart, slik at folk får mest mulig tid til å sette av datoen

**Comment by MariaSaether** [comment]
Purret opp Work-work nå,- de skulle sende tilbud på mat/drikke/leie av lokale. Var det bra oppmøte på siste meetup?
Skal få spikret dette ila uka, så kan vi annonsere ☺

Vennlig hilsen Maria

**Comment by iver56** [comment]
Flott! :) På forrige meetup (Workshop) var det 25 påmeldte. I tillegg var det ca. 12 personer på venteliste pga. begrensning på antall deltakere. Det var ca. 15-20 personer som dukket opp. Det gikk med 9 store pizzaer da.

**Comment by MariaSaether** [comment]
Hei Iver!
Vi blir nok enige med Work Work om en ordning, så det er bare å annonsere meetup 11.mai.
Fint om du legger til vår logo på meetup-siten, slik at vi står som arrangør ☺ Logo som kan benyttes finner du her: Inmeta-logo<https://www.google.no/search?q=inmeta+logo&espv=2&source=lnms&tbm=isch&sa=X&ved=0ahUKEwim-e_AibPTAhWrHpoKHVahBPcQ_AUIBigB&biw=1536&bih=735#imgrc=zu5Gpcxk9oCzrM>


Vennlig hilsen Maria

**Comment by iver56** [comment]
Flott, da annonserer jeg meetupen i løpet av dagen, og legger til Inmeta som sponsor :)

Tid: 2017-05-11 (torsdag) kl. 18:00

Sted: Møterommet på Work-Work

Antall deltakere: maks ca. 40

Ref avtale med Work-Work: Jeg er medlem på Work-Work, og jeg kan booke møterommet gratis én gang i uka. Når det gjelder servering kan man evt gjøre det enkelt og bare bestille pizza eller noe annet.

Høres det greit ut?

**Comment by iver56** [comment]
@MariaSaether Blir foredraget på norsk eller engelsk?

**Comment by MariaSaether** [comment]
Strålende.
Dersom det blir stor interesse så får vi flytte til Baren, slik at vi får med flest mulig deltakere.

Vennlig hilsen Maria

**Comment by MariaSaether** [comment]
Han holdt det på engelsk i Oslo, så det enkleste er å kjøre på engelsk her også ☺
Han snakker for øvrig flytende norsk, så alle kan stille spørsmål på norsk om de ønsker.

Vennlig hilsen Maria

**Comment by iver56** [comment]
https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/239354791/

**Comment by iver56** [comment]
- [x] Møterom booket 2017-05-11 fra ca. kl. 17:45 til 19:45
- [x] Postet link på https://www.facebook.com/groups/486811498194880/
- [x] Postet link på http://work-work.no/event/
