### ISSUE TITLE
Lime: Explaining the predictions of any machine learning classifier

### ISSUE THREAD

**Issue by iver56** [trondheim-machine-learning-meetup/meetups#7]
Tenker at en meetup om dette ville ha vært interessant:
https://github.com/marcotcr/lime

Noen som vil holde foredrag eller workshop?

**Comment by MariaSaether** [comment]
Hei!
Vi kan ta denne, William Naylor hos oss har allerede hatt tilsvarende presentasjon. Hva med ca. medio mars? (Vi bør unngå OsloBigDataDay, 13.mars)

Maria

**Comment by iver56** [comment]
Ja, det høres bra ut. Bare gi beskjed når du finner ut hvilken dato som passer best ??
________________________________

**Comment by MariaSaether** [comment]
Den er god!
Hvis du kan legge til et par av våre data scientister til ML-github’en så tror jeg det er hensiktsmessig. Jeg rekker ikke å følge opp så godt som jeg gjerne skulle ønske…
Github-kontoer:
WilliamNaylor (WilliamRNaylor, muligens….)
HuaminRen (huamin.ren@inmeta.no)

Vennlig hilsen Maria

**Comment by WillRNaylor** [comment]
Ja, jeg gjør dette.

**Comment by iver56** [comment]
https://twitter.com/sameer_/status/959605901580800001

**Comment by iver56** [comment]
@WillRNaylor Jeg foreslår torsdag 5. april kl. 18. Passer dette tidspunktet for deg?

Btw, møterommet på Work-Work er under oppussing akkurat nå. Jeg snakker med Sverre om å bruke DIGS i stedet.

**Comment by WillRNaylor** [comment]
Hei, de passer greit for meg. De eneste spørsmål er om vi burde vente en uke til. Tror du at det er mange som er fortsatt på påsker ferie da?

**Comment by iver56** [comment]
Vi kan godt vente en uke til ja :) Hva med f.eks. tirsdag 10. april kl. 18?

**Comment by WillRNaylor** [comment]
Yep, det høres perfekt.

**Comment by iver56** [comment]
Bra! Vi trenger forresten en liten beskrivelse til meetupen :) Vil du skrive den? Den trenger ikke å være så lang

**Comment by WillRNaylor** [comment]
Yep, jeg kan skriver den, og kanskje bare legge det ut her. Eller kan jeg oppretter meetup'en sjøl?

**Comment by iver56** [comment]
Bare legg den inn som kommentar her du, så kan jeg lage "Draft" av meetupen på meetup.com etterpå. Jeg legger deg til som co-organizer der, så kan du gjøre endringer i ettertid hvis du ønsker det :)

**Comment by WillRNaylor** [comment]
Great, takk.

**Comment by MariaSaether** [comment]
Høres bra ut, for min del, så lenge det passer for deg, William.

Vennlig hilsen Maria

**Comment by iver56** [comment]
@WillRNaylor Work-Work forteller at de kan tilby oss plass i baren (første etasje) mandag 9. april, siden de pusser opp i andre og tredje etasje nå. Høres det ut som en grei deal? Blir kanskje litt bakgrunnsstøy fra randoms i baren, men jeg regner med at du kan få låne mikrofon for å kompensere.

Alternativet er å leie lokaler hos DIGS, men det blir i så fall en ekstra kostnad.

PS: Work-Work bygger et fellesrom i tredje etasje som blir ferdig senere.

**Comment by WillRNaylor** [comment]
Hei Iver,

Ja, første etasje høres OK, og 9. april passer til meg så vi tar det. Nedenfor er en beskrivelse som kan brukes på meetup siden:

LIME (Local Interpretable Model-agnostic Explanations), is an algorithm for explaining why a classifier made the prediction it did. It works for any type of classifier (decision tree, NNs... ). The algorithm find which 'parts' (for example words for a text input) of the input are most important when the ML classifier decides which class it should be assigned to. A fun intro video and the github package are given below.

In the talk William Naylor, from Inmeta, will discuss what the algorithm is and how it works. Then give some concrete examples of it in use, and some ideas for use. We will also discuss the various pitfalls of the algorithm, and the follow up algorithm: anchors.

https://www.youtube.com/watch?v=hUnRCxnydCc
https://github.com/marcotcr/lime/

**Comment by iver56** [comment]
Flott! Jeg har opprettet draft av meetupen: https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/248434343/

Jeg har også gitt beskjed til Sverre (barsjef @ Work-Work) om at vi takker ja til tilbudet om å låne baren 9. april kl. 18. Venter på svar.

Er det forresten meningen at meetupen skal være uten servering? I så fall kan vi kanskje skrive det eksplisitt i meetup-beskrivelsen.

**Comment by iver56** [comment]
Har fått bekreftelse på reservasjon av baren.

La til følgende tekst på meetup-beskrivelsen nå:

> Intended audience: People who want to learn more about the technical details on trust and explainability/interpretability in AI.
> Food and drinks can be bought in the bar

Hvis dette ikke stemmer, kan du gå inn og endre teksten selv på https://www.meetup.com/Trondheim-Machine-Learning-Meetup/events/248434343/edit/

Jeg satser på å annonsere meetupen i ettermiddag. Høres det greit ut?

**Comment by MariaSaether** [comment]
Takk, Iver!
Når det gjelder servering så er det vel slik at dersom vi benytter lokalet i baren så kan vi ikke bestille pizza/ta med egen drikke?
Jeg må i tilfelle undersøke litt priser fra Work-work før vi sier noe om servering denne gangen.

Vennlig hilsen Maria

**Comment by iver56** [comment]
Work-Work har gitt oss lov til å bestille pizza og spise den i baren under arrangementet. Work-Work har ikke bedt om ekstra betaling for dette. Ønsker du å skaffe pizza til meetupen, så er det selvfølgelig positivt :) Vil du det?

**Comment by MariaSaether** [comment]
Da blir det pizza, ja 😊

Vennlig hilsen Maria

**Comment by WillRNaylor** [comment]
Alt ovenfor høres bra til meg. Jeg har lagt til på meetup side at vi skal ha pizza. Takk dere to, William.

**Comment by iver56** [comment]
Flott 👍 Meetupen publisereres nå

**Comment by iver56** [comment]
Her er noen flere prosjekter som kanskje er relevant å nevne under meetupen:

* https://github.com/tensorflow/lucid
* https://github.com/experiencor/deep-viz-keras#examples
